"""Added admin flag to user

Revision ID: 042872098358
Revises: 2bd2597d9e63
Create Date: 2026-04-11 08:34:58.484769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042872098358'
down_revision = '2bd2597d9e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
